Resources:
  ChatWebsocketConnections:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-websocket-connections
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  S3ProfileImages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.imagesBucketName}
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
      AccessControl: PublicRead
  ProfileImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3ProfileImages
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.imagesBucketName}/*
  S3ChatData:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.chatDataBucketName}
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
      AccessControl: PublicRead
  ChatDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3ProfileImages
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.chatDataBucketName}/*
