service: telegram-websockets

provider:
  name: aws
  stage: prod
  region: eu-central-1
  memorySize: 512
  timeout: 30
  runtime: nodejs10.x
  tracing:
    lambda: true
  environment:
    IS_LOCAL: ${env:IS_LOCAL}
    IMAGES_BUCKET_NAME: ${self:custom.imagesBucketName}
    BOT_TOKEN: ${env:BOT_TOKEN, file(./config.json):BOT_TOKEN}
    region: ${self:provider.region}
  iamRoleStatements:
    ${file(roleStatements.yml)}

functions:
  connect:
    handler: src/handlers.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/handlers.disconnect
    events:
      - websocket:
          route: $disconnect
  stats:
    handler: src/handlers.stats
    events:
      - websocket:
          route: stats
  broadcastStats:
    handler: src/handlers.broadcastStats
    events:
      - http:
          path: /
          method: get

custom:
  imagesBucketName: chat-profile-images
  serverless-offline:
    port: 4000
  webpack:
    packager: 'yarn'

plugins:
  - serverless-webpack
  - serverless-offline

resources:
  ${file(resources.yml)}
